const { exec } = require('child_process');
const util = require('util');
const execPromise = util.promisify(exec);

async function createBranchAndPR(ticketId, task, jobId) {
    const branchName = `feature/${ticketId}`;
    const commitMessage = `feat(${ticketId}): ${task.substring(0, 50)}`;
    const prTitle = `feat(${ticketId}): ${task.substring(0, 60)}`;
    const prBody = `## Ticket: ${ticketId}\n\n## Task\n${task}\n\n## Changes\n- Generated by Dev Agent\n\n## Test Results\n- Code generated successfully`;

    try {
        // Check if branch exists and switch/delete
        const { stdout: branchCheck } = await execPromise(`git branch --list ${branchName}`);
        if (branchCheck.trim()) {
            await execPromise(`git branch -D ${branchName}`);
        }
        
        // Create and switch to branch
        await execPromise(`git checkout -b ${branchName}`);
        console.log(`[${jobId}] Created branch: ${branchName}`);
        
        // Add all changes
        await execPromise(`git add .`);
        
        // Check if there are changes to commit
        const { stdout: statusOutput } = await execPromise(`git status --porcelain`);
        if (!statusOutput.trim()) {
            console.log(`[${jobId}] No changes to commit`);
            await execPromise(`git checkout main`);
            return { success: false, reason: "no_changes" };
        }
        
        // Commit changes
        await execPromise(`git commit -m "${commitMessage}"`);
        console.log(`[${jobId}] Committed: ${commitMessage}`);
        
        // Push branch
        await execPromise(`git push -u origin ${branchName}`);
        console.log(`[${jobId}] Pushed branch: ${branchName}`);
        
        // Create PR using GitHub CLI
        const prResult = await execPromise(`gh pr create --title "${prTitle}" --body "${prBody}" --base main --head ${branchName}`);
        console.log(`[${jobId}] PR created: ${prResult.stdout}`);
        
        // Switch back to main
        await execPromise(`git checkout main`);
        
        return { success: true, branch: branchName, prUrl: prResult.stdout.trim() };
    } catch (error) {
        console.error(`[${jobId}] Git error:`, error.message);
        return { success: false, error: error.message };
    }
}

module.exports = { createBranchAndPR };
